name: Agile Partners
favicon: null
layout_spectrum: 0.6455247267149389
typography_spectrum: 0.8014092587400228
title: DÃ© maat in ondernemen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.543287318199873
  lightness: 0.44935982720926404
  saturation: 0.03957232483662665
  rhythmicContrast: 0.4993430864997208
purpose: []
